FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends build-essential python3 python3-dev python3-pip python-is-python3 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pandas sympy pysam pyvcf3

COPY variant_interpretation.py  /opt/variant_interpretation/
COPY vcf_to_pandas_dataframe.py /opt/variant_interpretation/
COPY coverage.py                /opt/variant_interpretation/

ENV PYTHONPATH=$PYTHONPATH::/opt/variant_interpretation
ENV PATH=$PATH:/opt/variant_interpretation
