FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends python3 python3-pip python-is-python3 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pandas

COPY lims_report.py  /opt/lims_report/
ENV PATH=$PATH:/opt/lims_report
